from enum import Enum

class Company(Enum):
    SOCIETATEA_ENERGETICA_ELECTRICA = "EL",
    FONDUL_PROPRIETATEA = "FP",
    OMV_PETROM = "SNP",
    BANCA_TRANSILVANIA = "TLV",
    TRANSPORT_TRADE_SERVICES = "TTS",
    CNTEE_TRANSELECTRICA = "TEL",
    SNTGN_TRANSGAZ = "TGN",
    SNGN_ROMGAZ = "SNG",
    GROUP_SOCIETE_GENERALE = "BRD",
    EVERGENT_INVESTMENTS = "EVER",
    ERSTE_GROUP_BANK = "EBS",
    PURCARI_WINERIES = "WINE",
    MEDLIFE = "M",
    SIMTEL_TEAM = "SMTL",
    NOROFERT = "NRF",
    SAFETECH_INNOVATIONS = "SAFE",
    AROBS_TRANSILVANIA_SOFTWARE = "AROBS",
    AGROSERV_MARIUTA = "MILK"